branches:
  only:
    - master

image: Visual Studio 2022
configuration: Release
build:
  verbosity: detailed

clone_script:
  - git clone --recurse-submodules https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

install:
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

  - appveyor DownloadFile https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/LLVM-13.0.1-win64.exe -FileName llvm-installer.exe
  - START /WAIT llvm-installer.exe /S /D=C:\"Program Files\LLVM"

notifications:
  - provider: Email
    to:
      - patryk.czachurski@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

before_build:
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - cd C:\projects\hypersomnia

build_script:
  - mkdir nin
  - cd nin
  - mkdir %CONFIGURATION%
  - cd %CONFIGURATION%
  - cmake -G Ninja -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_LINKER=lld-link -DARCHITECTURE="x64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DGENERATE_DEBUG_INFORMATION=0 -DBUILD_DEBUGGER_SETUP=0 -DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64 ../..
  - ninja

test_script:
  - cd ../../hypersomnia
  - ps: '& ../cmake/test_pack_upload.ps1 -configuration $env:CONFIGURATION -console_mode 0'

