environment:
  ARTIFACT_UPLOAD_KEY:
    secure: xukZvGw6KB1WAGopzJKSOi88Xs+CvljlItMguKJ5AUL7XesfcFYTBqjPWmNufZwyN4hqV3n2ZD+aP/PsEcv3CyjLPZ5+7doRFSoNcVWfoboA55sVWGIqaVZmzsvM9Pu02L1Rtb0teJdsqFOIPZMDwzSQfeBeCflTdzFC1pw47GaKUvfRFkCZZFgvcWPKw+cZwa0DUqwRvTIl7qqkBXuKqYinXk/eONsT7MubZMAeJdR06grGJaVMDOqMMpMJ5EjOWL368a+v1lMzibR8SdjZcI3ZJq27xoMI2GdWOKqD/JCP9FwwRmFZziYh7EQpbaeyDWZgvQeZLqsJnZV9IqoeFlwQ58x3ntmfS3yyIZUD9BCyDr+DS5dNP+NjX/D50TtdLJQvkQMifKBjmZfMNxg8k8mSU950uNZdIPYjO/0vW/QPAWsvIVbR/AGPWhW9DdkxcZYSxw6Jrdtbw1y4prEZ516J/2zJMfI5yQLd6Fn1HdPBxI02AOWJhC/tninGdjqM1dHf7UQ0W4rWzYHUZhkVHYwwyw9a/6MAmUCEipPXiE+xVtaI7QqpVFdXS9rc5f0vZfHTp50klLBp5w5jfCkXC2mW5VNE0e9UaMDdcozB7HGmRNisWoPQd20xbrEFmWFU46exVHR/SlNb8BiEjoHdBZaTJJF4DMM6BFJW6zq9n9pNiGjc9ei/3IBFFPBaa/mc37QCd6DlpyXnqj3GYPivmtAWgi/4/7uOmzt/QFO+2UwdcxxrrqAgk4VeU99MTeICttfb+hU3I/qWC8WNm1Vt11ye73qq6YVL1jMhmcT8p+if/pjEIpjsR9dAjueAqPdbAEoV8DuV48ncnmpHkoeOuG06+G8Sz/AVFC9HXCisYQnF6zmNgoJV/oI7pwJRGZiBsuX+f9G1ddfAGnD3bEypfw==
    
version: 1.0.{build}
branches:
  only:
    - master

image: Visual Studio 2022
configuration: Release
build:
  verbosity: detailed

clone_script:
  - git clone --recurse-submodules https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

install:
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

  - appveyor DownloadFile https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/LLVM-13.0.1-win64.exe -FileName llvm-installer.exe
  - START /WAIT llvm-installer.exe /S /D=C:\"Program Files\LLVM"

notifications:
  - provider: Email
    to:
      - patryk.czachurski@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

before_build:
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - cd C:\projects\hypersomnia

build_script:
  - mkdir nin
  - cd nin
  - mkdir %CONFIGURATION%
  - cd %CONFIGURATION%
  - cmake -G Ninja -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_LINKER=lld-link -DARCHITECTURE="x64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DGENERATE_DEBUG_INFORMATION=0 -DBUILD_PROPERTY_EDITOR=0 -DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64 ../..
  - ninja

test_script:
  - cd ../../hypersomnia
  - ps: '& ../cmake/test_pack_upload.ps1 -artifact_upload_key $env:ARTIFACT_UPLOAD_KEY -configuration $env:CONFIGURATION -console_mode 0'

